
#define bh {
#define beezras_hashem {
#define shkoyach }
#define kabbalah asm
#define hameivin_yavin auto
#define tzvei_dinim bool
#define hadran_alach break
#define tzad case
#define nebech catch
#define oys char
#define the_hock cin
#define sugya class
#define muktzeh const
#define is_this_muktzeh const_cast
#define nu_nu continue
#define be_machriz cout
#define lmayseh default
#define zatzal delete
#define maysah do
#define gantze_chalakim double
#define pum_fakert else
#define minyan enum
#define befeirush explicit
#define hotzaah export
#define be_mefarsem extern
#define or_youre_a_kofer final
#define chalakim float
#define do_hishtadlus for
#define chaveir friend
#define ayein_sham goto
#define efsher if
#define the_pasuk_says inline
#define bli_ayin_hara int
#define gantz long
#define letzoirech_gufo mutable
#define shitta namespace
#define shlita new
#define melachas operator
#define rc_cola pop
#define reshus_hayachid private
#define karmelis protected
#define reshus_harabbim public
#define be_metzareif push_back
#define bezrizus register
#define pilpul reinterpret_cast
#define pasken return
#define a_bissel short
#define hechshered signed
#define do_we_have_a_minyan sizeof
#define ein_od_milvado static
#define naaseh_adam_betzalmeinu static_cast
#define meimra string
#define kobetz struct
#define chakira switch
#define kal_vachomer template
#define by_us this
#define be_moycheh throw
#define im_yirtzeh_hashem try
#define the_halacha_is typedef
#define agudah union
#define not_hechshered unsigned
#define holding using
#define svara virtual
#define narrishkeit void
#define its_not_pashut volatile
#define until_mashiach_comes_or(expr) while(!(expr))
#define emes true
#define sheker false
#define hearah #pragma FAKE_PRAGMA
#define kim_li #define
#define rabboisai endl
#define nisht !
#define HOSHIA 1
#define ESNOT2 2
#define AMECHA 3
#define UVAREICH 4
#define ESNOT5 5
#define NACHALASECHA 6
#define UREIM 7
#define VENASEIM 8
#define AD 9
#define OYLEM 10
