#define auto hameivin_yavin
#define bool tzvei_dinim
#define class sugya
#define enum minyan
#define float chalakim
#define int bli_ayin_hara
#define long gantz
#define short a_bissel
#define char oys
#define const muktzeh