#!/bin/bash

python3 checkflags.py "$@"
if [ $? -ne 0 ] ; then exit 1 ; fi

g++ -x c++ -std=c++11 "$@" -E -Dbe_soymech_on=#include | g++ -x c++ -std=c++11 -E -Dfalse=FLAG_FOUND_FALSE - | python3 checkfalse.py "$@"
if [ $? -ne 0 ] ; then exit 1 ; fi

# Now compile for real

g++ -x c++ -std=c++11 "$@" -E -Dbe_soymech_on=#include -Dkim_li=#define | \
 g++ -x c++ -std=c++11 -E --imacros=CONVERT_TO_CPP.cpp - | \
 g++ -x c++ -std=c++11 - 2>&1 | \
 g++ -x c++ -std=c++11 -E --imacros=UNTYPE.cpp - -std=c++11 -P | \
 python3 process_output.py